[package]
name = "khalse_pm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.10.0-rc.4"
libc = "0.2.117"
rand = "0.8.4"
lazy_static = "1.3.0"

[lib]
crate-type = ["cdylib"]
