/* Header generated by cbindgen from rust lang. Note that this is a C++ header */

#pragma once

/* Generated with cbindgen:0.20.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>


using CSTR = const char*;


extern "C" {

bool close_connection(int conn_id);

int32_t connect_smtp(CSTR host, CSTR username, CSTR password);

/// RIP Error handling!
/// Error handling must be done properly
bool send_mail(int conn_id, CSTR sender, CSTR to, CSTR subject, CSTR body);

} // extern "C"
